#!/bin/sh
#set -x
vim $VIM_DEFAULT_ARG \
  -c ':so $VIM_XML_RT/autoload/xmlformat.vim' \
  -c ':set formatexpr=xmlformat#Format() ts=2 sw=0 sts=-1' \
  -c 'norm! Vgq' \
  -c ':saveas! output.xml' \
  -c ':q!'  input.xml
