#!/bin/sh
#set -x
vim --clean \
  -c ':so $VIM_XML_RT/autoload/xmlformat.vim' \
  -c ':set formatexpr=xmlformat#Format() ts=2 sw=0 sts=-1 tw=80' \
  -c '4norm! gql' \
  -c '7norm! gql' \
  -c ':saveas! output.xml' \
  -c ':q!'  input.xml
