#!/bin/sh
vim $VIM_DEFAULT_ARG \
--cmd ':set rtp^=$VIM_XML_RT' \
-c 'set ts=2 sw=0 sts=-1 et' \
-c 'exe ":norm! I<tag>\<CR><another>\<CR>world\<CR></another>\<CR></tag>"' \
-c ':saveas! output.xml' \
-c ':q!' \
input.xml
